import './globals.css'
import type { Metadata } from 'next'
import Modal from "@/components/Modal";

export const metadata: Metadata = {
  title: 'Trello Clone',
  description: 'Generated by Andii Sivak',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        {children}
        <Modal />
      </body>
    </html>
  )
}
